Feat subtraction
mr-gilberto/onboardingmodule2 pull request #3
Opened 2018-05-09 18:56 UTC by mr-gil

Created feature subtraction

Testing done: Pixel 2 API 27

Author: gilberto.ibarra@globant.com

2018-05-10 16:17 UTC, gaston-mira-glb commented on app/src/main/java/module2/globant/calculator/mvp/model/CalculatorModel.java
> +                return a + b;
add break for each case

2018-05-10 16:26 UTC, gaston-mira-glb requested changes

2018-05-10 16:26 UTC, gaston-mira-glb commented on app/src/main/java/module2/globant/calculator/mvp/presenter/CalculatorPresenter.java
> +            return;
it's better if you use 
```java 
if (activity != null) {
     RxBus.subscribe(activity, new OperationButtonBusObserver() 
```

The code is more legilable

2018-05-10 16:26 UTC, gaston-mira-glb commented on app/src/main/java/module2/globant/calculator/mvp/presenter/CalculatorPresenter.java
> +        if (activity == null) {
here the same

2018-05-10 16:26 UTC, gaston-mira-glb commented on app/src/main/java/module2/globant/calculator/mvp/view/CalculatorView.java
> +    @BindView(R.id.result_label)
you can put this in the same line
```java
@BindView(R.id.result_label) TextView resultLabel;
```

2018-05-10 16:26 UTC, gaston-mira-glb commented on app/src/main/res/layout/activity_main.xml
> +        android:textSize="18sp"/>
use dimens please

2018-05-10 16:26 UTC, gaston-mira-glb commented on app/src/main/res/layout/activity_main.xml
> +        android:textSize="27sp" />
here too

2018-05-10 21:45 UTC, fanky10 requested changes

2018-05-10 21:45 UTC, fanky10 commented on app/src/main/java/module2/globant/calculator/mvp/model/CalculatorModel.java
> +                case Constants.SUBTRACTION:
please fix tab alignment

2018-05-11 12:43 UTC, gaston-mira-glb commented on app/src/main/java/module2/globant/calculator/mvp/model/CalculatorModel.java
> +             case Constants.SUBTRACTION:
please fix tabulation

2022-02-23 20:12 UTC, merged